# Generated by Django 2.1.1 on 2018-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
